### ISSUE TITLE
Error while importing new preset.

### ISSUE THREAD

**Issue by cameronfrazier** [DanielKote/Foreman2#4] opened 2021-11-05 10:52 UTC
Interesting tool I'd like to try out, but I had an issue however...

While trying to import a new preset to match my current game, an window appears stating that the export from Factorio could not be completed.
![Error Window](https://user-images.githubusercontent.com/7953204/140497065-c6453f80-8e68-41ef-b659-e6549403d926.png)

Foreman2 is running release titled "Foreman v2.0 - dev.4"

Factorio is running via Steam on Windows 10 Pro, using the latest Experimental release (1.1.45)
![Factorio Version and Build](https://user-images.githubusercontent.com/7953204/140497541-87a373ec-52cc-4fc0-bc40-44b40d24fe05.png)

The game loads fine and without any mod conflicts, so I'm not sure the source of the error.
My current game is a SpaceX run, so there are a lot of mods.

Error Logs:
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/7482483/errorlog.txt)
[errorExporting.json.txt](https://github.com/DanielKote/Foreman2/files/7482486/errorExporting.json.txt)

Thanks, and please let me know if I can help figure out the issue.

**Comment by DanielKote** [comment] 2021-11-05 15:22
This is now the second time I have heard about this issue, and unfortunately both times I cant reproduce it. For some reason the first part of the export doesnt complete, but the second part does.
Could you please provide your config.ini file? It should be in:  c:\ users \ name \ appdata \ roaming \ factorio \ config \ config.ini

**Comment by DanielKote** [comment] 2021-11-05 15:50
Also, I switched out the export method, so give dev.5 a try and tell me what happens.

**Comment by cameronfrazier** [comment] 2021-11-05 16:48
Thanks for the quick response.

I tried the dev.5 version (clean install) but encountered the same result.

![Error Message_dev.5](https://user-images.githubusercontent.com/7953204/140545416-8f1fabcf-bf3e-4e0a-a61a-47397b62899f.png)

Error Logs
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/7487520/errorlog.txt)
[errorExporting.json.txt](https://github.com/DanielKote/Foreman2/files/7487522/errorExporting.json.txt)

Factorio config.ini
[config.ini.txt](https://github.com/DanielKote/Foreman2/files/7487598/config.ini.txt)

I then validated my local files and ensured I was locked to Factorio release 1.1.45, but I was still getting the same error.

**Comment by DanielKote** [comment] 2021-11-05 18:05
thats unfortunate. Again please. I updated the dev.5, so just try it again.

**Comment by cameronfrazier** [comment] 2021-11-05 18:41
Thanks again for the quick response.

No change with the new build. Again it was a clean install.

I also tried removing all mods other than base (run game, disable all mods, reload, exit, rename mods folder, run game, create new game and save so that the current is vanilla, exit), trying to see if there an issue isolated to a particular mod, but that had no effect and the error was still thrown.

Error logs are attached, including the related game log, just in case it helps you.
[factorio-current.log](https://github.com/DanielKote/Foreman2/files/7488199/factorio-current.log)
[errorExporting.json.txt](https://github.com/DanielKote/Foreman2/files/7488232/errorExporting.json.txt)
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/7488233/errorlog.txt)

I'm not in a position right now to do a full/clean install of Factorio, but I can try that in a couple days maybe.
Would there be a particular version of Factorio I should try? Something you know works? 

Cheers,

**Comment by DanielKote** [comment] 2021-11-05 18:49
Well, at this point I dont know what doesnt work, so I cant exactly recommend a working version - I have been trying to get the import to fail on my end for the better part of the day with no results.
If you have time, could you try a few things?
1 - copy the mod (foremanexport_1.0.0) to your mods directory and try again.
2 - copy the mod again (it gets deleted after every import), find your factorio exe file (it should be in steam/steamapps/common/factorio/bin/x64), create a 'test.bat' file with the following line: "factorio.exe --verbose --instrument-mod foremanexport" (without any quotes), and run it. Steam will likely ask you if you really want to do this, so ok that and include the resulting factorio-current.log.

**Comment by cameronfrazier** [comment] 2021-11-05 19:39
Hey, I ran those scenarios, plus a one with all of the SpaceX mods, seeing if I could trigger something interesting. No luck sadly. 

I need to sign off for for the night, but can keep working on this on Monday. 
I'm starting to think it's a strange setting on my end, so I'll try a full re-install next week, see if we can't narrow down the issue.
If you think of something I should try, please post it here and I'll give it a shot.

Cheers

**Scenario 1:** 
- Manual copy of "foremanexport_1.0.0"
- Launching Foreman2 and trying preset import
- Result: No change, same error is shown
[factorio-current.log.manual_mod_install.txt](https://github.com/DanielKote/Foreman2/files/7488361/factorio-current.log.manual_mod_install.txt)
[errorExporting.json.manual_mod_install.txt](https://github.com/DanielKote/Foreman2/files/7488373/errorExporting.json.manual_mod_install.txt)
[errorlog.txt.manual_mod_install.txt](https://github.com/DanielKote/Foreman2/files/7488376/errorlog.txt.manual_mod_install.txt)

**Scenario 2:**
- Manual copy of "foremanexport_1.0.0"
- Launch Factorio via bat file as instructed
- Result: No noticeable errors thrown
[factorio-current.log.manual_mod_install_manual_exec.txt](https://github.com/DanielKote/Foreman2/files/7488425/factorio-current.log.manual_mod_install_manual_exec.txt)

**Scenario 2+SpaceX:**
- Reloaded all mods from backup
- Ran Factorio, loaded SpaceX save to ensure the current ("Continue") game is the SpaceX save
- Exit
- Manual copy of "foremanexport_1.0.0"
- Launch Factorio via bat file as instructed
- Result: No noticeable errors thrown
[factorio-current.log.manual_mod_install_manual_exec_SpaceX.txt](https://github.com/DanielKote/Foreman2/files/7488466/factorio-current.log.manual_mod_install_manual_exec_SpaceX.txt)

**Comment by DanielKote** [comment] 2021-11-05 21:37
Ok, I once again re-done the import process to include a compatibility mode. This should ignore the entire instrumental mode that I use in order to ensure I grab the data after all other mods have finished their job, and instead runs the import mod as a standard mod (just with an auto-created mod dependency list that includes all the mods in the target folder). If this still fails, I would probably have to give up on this seeing as how I have no way of reproducing the issue.

Give it a try - Dev.6, and be sure to check the 'compatibility mode' checkbox in the import window.

**Comment by Thiske0** [comment] 2021-11-06 15:02
I've had this problem or a similar one for me it was a problem with permissions moving the foreman install to C:\Users\(urrent user)\AppData\Roaming\Foreman seemed to solve the problem for me.

**Comment by DanielKote** [comment] 2021-11-06 17:33
Could you elaborate on that? which permissions? Does running the app in 'admin' work? I have been trying to figure out where the issue was for a while now, so any help would be appreciated.

**Comment by Thiske0** [comment] 2021-11-06 19:14
it was a expected issue because i ran it as a normal unprivileged user and it was located in C:\Program Files so when it tried writing a file it was off course denied

**Comment by Thiske0** [comment] 2021-11-06 19:18
however when i installed the latest version dev 6 it somehow produced the same error as mentioned here
so it has to be an issue with something changed between dev 4 and 6
compat mode gave the same result
going back to version 4 and it is working again (or at least getting to 96% but thats another promblem)

**Comment by Thiske0** [comment] 2021-11-06 20:22
ah of course running it once doesn't work for version 4 but the second time it does and for version 6 it fails both times wihout the data-final-fixes.lua
however when added to version 4 it works first time but for version 6 it still fails
its getting more confusing bye the minute
lt however is behaving determenistic this means redeleting the data-final-fixes.lua from version 4 and relaunching it makes it not work the first time again but the second time it does.
conclusion: it only works in version 4 with the data-final-fixes and without it after the second time.
(its always about the foremanexport mod)
note that these test are beig done in quick sucsession so this could change things regarding to the factorio side of this
(since it seems factorio isn't fully unloaded after the first launch even accros versions)

**Comment by DanielKote** [comment] 2021-11-06 23:19
well, data-final-fixes would cause version 4 to fail - that makes perfect sense (the output text structure is different), so the first time it would fail and the second time it would work (as in - without the data-final-fixes).
So without any manual copying of files - 
- V4 fails once, then succeeds on successive attempts
- V6 fails all the time (both in regular and in compatibility modes)
Did I get that right?
I also updated everything up to V7 just now, but this shouldnt impact the import issues (as I still have no idea what is going on). I did add a check for privileges, but I dont think that is an issue here.

**Comment by Thiske0** [comment] 2021-11-07 10:05
yes thats true but the wierd thing is v 4 doesn't fail with the data-final-fixes even wierder it works first try instead of only after the second time

**Comment by cameronfrazier** [comment] 2021-11-08 16:50
Hi @DanielKote, I'm back and have had a chance to do some tests (as well as starting to learn some of the ins and outs of Factorio modding...)

I had a chance to re-install the game this evening, and gave things another shot.

Running the latest version of Foreman2 results in the same error window:
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/7497665/errorlog.txt)
[errorExporting.json.txt](https://github.com/DanielKote/Foreman2/files/7497668/errorExporting.json.txt)

However... Loading the mod into Factorio, then running the game normally results in getting the output from the data-final-fixes
[factorio-current.log.dev8.manual_mod_install.txt](https://github.com/DanielKote/Foreman2/files/7497832/factorio-current.log.dev8.manual_mod_install.txt)
I've been able to repeat this, so I think the P1 export is working in non-instrument mode.

Figuring out what is going on during instrument mode is a taking me a bit longer to figure out.
Would you happen to have examples of working export log files, what Foreman is expecting, so I can have a look a bit more on my end? 
I'm worried that it's an issue particular to me, and I'd like to poke around a bit and see if I can get some better data for you, if it is not my system.

Thanks for all the help,

**Comment by DanielKote** [comment] 2021-11-08 22:09
Ok, so I am basically 100% sure that the issue lies with caching the data stage of the game. If I look at the errorExporting files, in all situations the actual data.lua files are never processed (for you), and instead you have the following line:
   0.240 Data stage cache loaded in: 0.226339 seconds.
Naturally this means that anything that I do in the data stage of the mod exporter (icon export), will not happen because the game just goes 'here - we have done this before, so why not use it?'. And never does any of the logging text since its not really meant to be used in such a way.
I am at the moment trying to get my setup to cache the files as well so I can get the error to happen, but for now could you go into your config.ini file and search for "cache-prototype-data" and ensure it is set to false? that might help out.

**Comment by DanielKote** [comment] 2021-11-08 22:38
So, I finally managed to reproduce the issue, and I was right - it was the caching of the data stage. Give a try at Dev.9 version, and (hopefully) it should solve the issues. If so, I can finally close this issue!

**Comment by cameronfrazier** [comment] 2021-11-09 00:41
Success!

Seems to work with both the cache turned on and off. 
I must have toggled that some time ago and forgot, I guess in the re-install I forgot to purge the settings...

Thanks for all the help in sorting out my issue!

Cheers

**Closed as completed** 2021-11-09 00:41 UTC

**Comment by DanielKote** [comment] 2021-11-09 01:22
Yep - I made sure that during the first stage of the import (creating the temporary save file) it ensures that the export mod is NOT included in the mod list, which means that when the mod is added (and enabled) during the second stage of the import (when it actually needs to process the data and control stages), Factorio has no option but to ignore the cache and run the full data cycle.
A bit convoluted, but I couldnt find anywhere in the Factorio commands how to force it to ignore cache (without changing the settings, and I kind of didnt want to touch them so as not to potentially impact the Factorio install).
Wow. What a ride.
Well, post a post on reddit when you get a cool enough graph built!

**Comment by cameronfrazier** [comment] 2021-11-09 01:45
Nice solution. 
If it's convoluted and it works... it works!
Thanks again!
