### ISSUE TITLE
Old DataCache object is not destroyed when reloading settings

### ISSUE THREAD

**Issue by arik123** [DanielKote/Foreman2#31] opened 2022-02-14 15:23 UTC
## Steps to reproduce:
1. Start foreman
2. Open settings
3. Go to Graph Options
4. Toggle `Load barelling crafting recipes`
5. Confirm
6. Observe memory usage

## Possible cause
There is most likely some reference to the old DataCache left even after it is replaced with the new one, so the GC keeps it alive.

**Comment by gillett-hernandez** [comment] 2022-11-20 23:09
i confirmed the cause by running a memory snapshot before and after and comparing reference counts. upon loading a new preset there's two unique `DataCache`s in memory. this might take a bit to fix since afaik you'd have to go through all references to `DataCache`s and maybe put breakpoints or otherwise investigate which references don't get reassigned to the newly constructed `DataCache`.

**Comment by mrozpara** [comment] 2022-11-21 12:44
IMHO: `DataCache` should be moved from `ProductionGraphView` to `mainForm` - that will allow to have multiple files (tabs) opened (first step to have it), and in meantime all references/assignment will have to be reviewed...

**Closed as completed** 2023-03-07 20:22 UTC
