### ISSUE TITLE
The icons have disappeared

### ISSUE THREAD

**Issue by flameSla** [DanielKote/Foreman2#112] opened 2024-11-05 13:07 UTC
I clicked the "Enable Dark Mode" checkbox.
I didn't like the mode, so I unchecked "Enable Dark Mode".
After that, the icons disappeared.

Reinstalling the program did not help.
Where are the program settings stored? How do I reset the settings?

**Comment by flameSla** [comment] 2024-11-05 13:12
![Untitled](https://github.com/user-attachments/assets/b815009d-de36-4d6a-a4c4-35c98e60fdb1)

**Comment by Olipro** [comment] 2024-11-05 14:47
I am not able to reproduce this when I toggle dark mode.

It sounds more to me like some necessary content got deleted from Foreman's folder and when you toggled dark mode, it triggered a redraw that could no longer find the icons. This is definitely the case if Foreman is still broken after closing and reopening it.

I would suggest that you go to settings and perform a fresh import of the preset you use. Make sure that Foreman is seeing any mods you're putting down graphs for.

**Comment by flameSla** [comment] 2024-11-05 15:06
I have completely deleted all Foreman files.
I unpacked all the files of their release archive, the problem remained. There are no icons.

Where are the program settings stored?
How do I reset the settings?

**Comment by Olipro** [comment] 2024-11-05 16:15
~~The settings live in the folder where you extracted it as `Foreman.exe.config` - if you nuked the whole thing, you would have nuked the settings.~~

They should be under `%LOCALAPPDATA%\Foreman`

**Comment by flameSla** [comment] 2024-11-05 16:29
Deleting the settings helped, the bug disappeared.
I have attached the settings for reproducing the bug.
[user.config.txt](https://github.com/user-attachments/files/17635586/user.config.txt)

**Comment by Olipro** [comment] 2024-11-07 08:55
Your problem was caused by setting `Maximum number of graphical objects` to `0` in your settings. Foreman treats this as you wanting to disable them, not as infinity.

Issue can be closed, but perhaps in future a warning message might be warranted when someone tries to set counter-productive values.

**Comment by flameSla** [comment] 2024-11-07 12:32
You can also add a button to reset the settings to default.

**Closed as completed** 2024-11-07 17:28 UTC
